{
 "title": "ADR _Dashboard_new",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "time", "label": "time", "query": "1d,7d,14d,30d,1m,2m,5m,1y" }
  ]
 },
 "panels": [
  { "title": "Übersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ALL ADR's",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT * FROM adr_entities LIMIT 50 "
    }
   ]
  },
  {
   "title": "Anzahl der Einträge pro Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT status, COUNT(*) AS Anzahl\nFROM adr_entities\nGROUP BY status;\n"
    }
   ]
  },
  {
   "title": "Letzten 5 Einträge",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT id, titel, random_date AS date\nFROM adr_entities \nORDER BY random_date DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "Gesamtentscheidungscounter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS Gesamtanzahl\nFROM adr_entities;\n"
    }
   ]
  },
  { "title": "Zeitauswertungen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Entscheidungsstatus nach Monat",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(random_date, 'YYYY-MM') AS year_month,\n    COUNT(CASE WHEN status = 'Deprecated' THEN 1 END) AS count_deprecated,\n    COUNT(CASE WHEN status = 'Active' THEN 1 END) AS count_active\nFROM\n    adr_entities\nGROUP BY\n    TO_CHAR(random_date, 'YYYY-MM')\nORDER BY\n    year_month;"
    }
   ]
  },
  {
   "title": "Desicions over Time by Month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(random_date, 'YYYY-MM') AS year_month,\n    COUNT(*) AS decision_count\nFROM\n    adr_entities\nGROUP BY\n    TO_CHAR(random_date, 'YYYY-MM')\nORDER BY\n    year_month;\n\n"
    }
   ]
  },
  {
   "title": "Desicions over Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    to_char(date_trunc('day', random_date), 'YYYY-MM-DD') AS day,\n    count(*) AS decision_count\nFROM adr_entities \nWHERE decisions IS NOT NULL\nGROUP BY day\nORDER BY day;\n"
    }
   ]
  },
  { "title": "Detaillierte Auswertung", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "ADR's nutzen die gleichen Artefakte",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n    SUBSTRING(\n        a.text,\n        position('[' in a.text) + 1,\n        position(']' in a.text) - position('[' in a.text) - 1\n    ) AS artifact_in_brackets,\n    STRING_AGG(CAST(ae.adr_entities_id AS VARCHAR), ',') AS adr_ids\nFROM\n    artifact a\nJOIN\n    adr_entities_artifacts ae ON a.id = ae.artifacts_id\nWHERE\n    position('[' in a.text) > 0 AND position(']' in a.text) > position('[' in a.text)\nGROUP BY\n    artifact_in_brackets\nORDER BY\n    artifact_in_brackets;"
    }
   ]
  },
  {
   "title": "Häufigkeit der Artefakte",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n    SUBSTRING(\n        a.text,\n        position('[' in a.text) + 1,\n        position(']' in a.text) - position('[' in a.text) - 1\n    ) AS artifact_in_brackets,\n    COUNT(*) AS count\nFROM\n    artifact a\nJOIN\n    adr_entities_artifacts ae ON a.id = ae.artifacts_id\nWHERE\n    position('[' in a.text) > 0 AND position(']' in a.text) > position('[' in a.text)\nGROUP BY\n    artifact_in_brackets\nORDER BY\n    count DESC;"
    }
   ]
  },
  {
   "title": "Relations between ADR's",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT\n    aer.adr_entities_id AS ADRID,\n    STRING_AGG(CASE WHEN r.txt LIKE 'enables %%' THEN regexp_result[1] END, ', ') AS enables,\n    STRING_AGG(CASE WHEN r.txt LIKE 'is enabled by %%' THEN regexp_result[1] END, ', ') AS enabled_by,\n    STRING_AGG(CASE WHEN r.txt LIKE 'is extended by %%' THEN regexp_result[1] END, ', ') AS extended_by,\n    STRING_AGG(CASE WHEN r.txt LIKE 'is deprecated by %%' THEN regexp_result[1] END, ', ') AS deprecated_by\nFROM\n    adr_entities_relations aer\nJOIN\n    relation r ON aer.relations_id = r.id\nLEFT JOIN LATERAL\n    REGEXP_MATCHES(r.txt, 'ADR ([0-9]+)') AS regexp_result ON true\nGROUP BY\n    aer.adr_entities_id\nORDER BY\n    ADRID;"
    }
   ]
  }
 ]
}